name = "CountdownSolver"
uuid = "7e945158-e9db-46ef-8867-8dbbec1b05b8"
authors = ["Sebastian Gonzato <sebastian_gonzato@protonmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
